language: java
dist: trusty
sudo: required
group: deprecated-2017Q4

jdk: openjdk8

#services:
#  - docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - _build
  - deps

before_install:
 - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
 - git lfs pull
 - sudo apt-get update -q
 - sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 -y
 - sudo apt-get install genisoimage -y

install:
 - mvn -N io.takari:maven:wrapper
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

branches:
  only:
    - dev

stages:
   - test

jobs:
  include:
     - stage: test
       script:
         - mvn clean test -P local
