version: "2"
services:
   app:
     build:
         context: .
         dockerfile: Dockerfile.build
     volumes:
         - "$HOME/.m2:/root/.m2"
     ports:
         - "8080:8080"
command: mvn clean test -P local